export const Genres  = [
    {
        id: 1,
        name: "Shonen",
        bold: true
    },
    {
        id: 2,
        name: "Seinen",
        bold: true
    },
    {
        id: 3,
        name: "Adventure",     
    },
    {
        id: 4,
        name: "Action", 
    },
    {
        id: 5,
        name: "Sci-Fi",      
    },
    {
        id: 6,
        name: "Drama",     
    },
    {
        id: 7,
        name: "Fantasy",     
    },
    {
        id: 8,
        name: "Supernatural",      
    },
    {
        id: 9,
        name: "Mystery",     
    },
    {
        id: 10,
        name: "Horror",     
    },
    {
        id: 11,
        name: "Psychological",      
    },
    {
        id: 12,
        name: "Romance",     
    },
    {
        id: 13,
        name: "Harem",     
    },
]

export const MangaProducts = [

    {
        title: "Chainsaw Man, Vol. 1",
        series: "Chainsaw Man",
        authors: ["Tatsuki Fujimoto"],
        language: "EN",
        rating: 5,
        isNew:true,
        isBestseller: true,
        discount: 20,
        numberOfRatings: 1,
        price: 269,
        desc: `Denji was a small-time devil hunter just trying to survive in a harsh world. After being killed on a job, he is revived by his pet devil Pochita and becomes something new and dangerous—Chainsaw Man!

        Denji’s a poor young man who’ll do anything for money, even hunting down devils with his pet devil-dog Pochita. He’s a simple man with simple dreams, drowning under a mountain of debt. But his sad life gets turned upside down one day when he’s betrayed by someone he trusts. Now with the power of a devil inside him, Denji’s become a whole new man—Chainsaw Man!`,
        pages: 224,
        date: "1.11.2021",
        categories: ["Shojo", "Action", "Supernatural"],
        imgCover: "https://media.libris.to/jacket/28209558_chainsaw-man-vol-1.jpg",
        imgPanels: ["https://i.pinimg.com/736x/07/28/b9/0728b970ae219619b83fb64ea3431020.jpg", "https://64.media.tumblr.com/acd466ceb19e78395e00bc2c22a5122c/6a975e344cbf7da6-ff/s500x750/428e250ae2303fa1bf22fee5e35992492dd74562.jpg",
         "https://pbs.twimg.com/media/Ew4ymZYWUAAt4Wd.jpg"],    
    },
    {
        title: "Chainsaw Man, Vol. 2",
        series: "Chainsaw Man",
        authors: ["Tatsuki Fujimoto"],
        language: "EN",
        rating: 5,
        isNew:true,
        isBestseller: true,
        discount: 20,
        numberOfRatings: 1,
        price: 239,
        desc: `Denji was a small-time devil hunter just trying to survive in a harsh world. After being killed on a job, he is revived by his pet devil Pochita and becomes something new and dangerous—Chainsaw Man!

        Denji’s a poor young man who’ll do anything for money, even hunting down devils with his pet devil-dog Pochita. He’s a simple man with simple dreams, drowning under a mountain of debt. But his sad life gets turned upside down one day when he’s betrayed by someone he trusts. Now with the power of a devil inside him, Denji’s become a whole new man—Chainsaw Man!`,
        pages: 196,
        date: "1.11.2021",
        categories: ["Shojo", "Action", "Supernatural"],
        imgCover: "https://media.libris.to/jacket/42142704_chainsaw-man-2-motorovka-vs-netopyr.jpg",
        imgPanels: ["https://i.pinimg.com/736x/07/28/b9/0728b970ae219619b83fb64ea3431020.jpg", "https://64.media.tumblr.com/acd466ceb19e78395e00bc2c22a5122c/6a975e344cbf7da6-ff/s500x750/428e250ae2303fa1bf22fee5e35992492dd74562.jpg",
         "https://pbs.twimg.com/media/Ew4ymZYWUAAt4Wd.jpg"],    
    },
    {
        title: "Chainsaw Man, Vol. 3",
        series: "Chainsaw Man",
        authors: ["Tatsuki Fujimoto"],
        language: "EN",
        rating: 5,
        isNew:true,
        isBestseller: true,
        discount: 20,
        numberOfRatings: 1,
        price: 229,
        desc: `Denji was a small-time devil hunter just trying to survive in a harsh world. After being killed on a job, he is revived by his pet devil Pochita and becomes something new and dangerous—Chainsaw Man!

        Denji’s a poor young man who’ll do anything for money, even hunting down devils with his pet devil-dog Pochita. He’s a simple man with simple dreams, drowning under a mountain of debt. But his sad life gets turned upside down one day when he’s betrayed by someone he trusts. Now with the power of a devil inside him, Denji’s become a whole new man—Chainsaw Man!`,
        pages: 196,
        date: "1.11.2021",
        categories: ["Shojo", "Action", "Supernatural"],
        imgCover: "https://media.libris.to/jacket/33210630_chainsaw-man-vol-3.jpg",
        imgPanels: ["https://i.pinimg.com/736x/07/28/b9/0728b970ae219619b83fb64ea3431020.jpg", "https://64.media.tumblr.com/acd466ceb19e78395e00bc2c22a5122c/6a975e344cbf7da6-ff/s500x750/428e250ae2303fa1bf22fee5e35992492dd74562.jpg",
         "https://pbs.twimg.com/media/Ew4ymZYWUAAt4Wd.jpg"],    
    },
    {
        title: "Chainsaw Man, Vol. 4",
        series: "Chainsaw Man",
        authors: ["Tatsuki Fujimoto"],
        language: "EN",
        rating: 5,
        isNew:true,
        isBestseller: true,
        discount: 20,
        numberOfRatings: 1,
        price: 269,
        desc: `Denji was a small-time devil hunter just trying to survive in a harsh world. After being killed on a job, he is revived by his pet devil Pochita and becomes something new and dangerous—Chainsaw Man!

        Denji’s a poor young man who’ll do anything for money, even hunting down devils with his pet devil-dog Pochita. He’s a simple man with simple dreams, drowning under a mountain of debt. But his sad life gets turned upside down one day when he’s betrayed by someone he trusts. Now with the power of a devil inside him, Denji’s become a whole new man—Chainsaw Man!`,
        pages: 244,
        date: "1.11.2021",
        categories: ["Shojo", "Action", "Supernatural"],
        imgCover: "https://media.libris.to/jacket/33396972_chainsaw-man-vol-4.jpg",
        imgPanels: ["https://i.pinimg.com/736x/07/28/b9/0728b970ae219619b83fb64ea3431020.jpg", "https://64.media.tumblr.com/acd466ceb19e78395e00bc2c22a5122c/6a975e344cbf7da6-ff/s500x750/428e250ae2303fa1bf22fee5e35992492dd74562.jpg",
         "https://pbs.twimg.com/media/Ew4ymZYWUAAt4Wd.jpg"],    
    },

    {
        title: "Berserk Volume 1",
        series: "Berserk",
        authors: ["Kentaro Miura"],
        isBestseller: true,
        discount: "35",
        language: "EN",
        rating: 5,
        numberOfRatings: 1,
        price: 334,
        desc: `His name is Guts, the Black Swordsman, a feared warrior spoken of only in whispers. Bearer of a gigantic sword, an iron hand, and the scars of countless battles and tortures, his flesh is also indelibly marked with The Brand, an unholy symbol that draws the forces of darkness to him and dooms him as their sacrifice. But Guts won't take his fate lying down; he'll cut a crimson swath of carnage through the ranks of the damned - and anyone else foolish enough to oppose him!`,
        pages: 224,
        date: "4.11.2003",
        categories: ["Seinen", "Action", "Supernatural"],
        imgCover: "https://www.slovart.cz/buxus/images/image_30623_19_v1.jpeg",
        imgPanels: ["https://i.pinimg.com/736x/07/28/b9/0728b970ae219619b83fb64ea3431020.jpg", "https://64.media.tumblr.com/acd466ceb19e78395e00bc2c22a5122c/6a975e344cbf7da6-ff/s500x750/428e250ae2303fa1bf22fee5e35992492dd74562.jpg",
         "https://pbs.twimg.com/media/Ew4ymZYWUAAt4Wd.jpg"],    
    },
    {
        title: "Berserk Volume 2",
        series: "Berserk",
        authors: ["Kentaro Miura"],
        language: "EN",
        isBestseller: true,
        discount: "35",
        rating: 5,
        numberOfRatings: 1,
        price: 360,
        desc: `His name is Guts, the Black Swordsman, a feared warrior spoken of only in whispers. Bearer of a gigantic sword, an iron hand, and the scars of countless battles and tortures, his flesh is also indelibly marked with The Brand, an unholy symbol that draws the forces of darkness to him and dooms him as their sacrifice. But Guts won't take his fate lying down; he'll cut a crimson swath of carnage through the ranks of the damned - and anyone else foolish enough to oppose him!`,
        pages: 240,
        date: "4.11.2004",
        categories: ["Seinen", "Action", "Supernatural"],
        imgCover: "https://media.libris.to/jacket/02750247_berserk.jpg",
        imgPanels: ["https://i.pinimg.com/736x/07/28/b9/0728b970ae219619b83fb64ea3431020.jpg", "https://64.media.tumblr.com/acd466ceb19e78395e00bc2c22a5122c/6a975e344cbf7da6-ff/s500x750/428e250ae2303fa1bf22fee5e35992492dd74562.jpg",
         "https://pbs.twimg.com/media/Ew4ymZYWUAAt4Wd.jpg"],    
    },
    {
        title: "Berserk Volume 3",
        series: "Berserk",
        authors: ["Kentaro Miura"],
        language: "EN",
        isBestseller: true,
        discount: 25,
        rating: 5,
        numberOfRatings: 1,
        price: 314,
        desc: `His name is Guts, the Black Swordsman, a feared warrior spoken of only in whispers. Bearer of a gigantic sword, an iron hand, and the scars of countless battles and tortures, his flesh is also indelibly marked with The Brand, an unholy symbol that draws the forces of darkness to him and dooms him as their sacrifice. But Guts won't take his fate lying down; he'll cut a crimson swath of carnage through the ranks of the damned - and anyone else foolish enough to oppose him!`,
        pages: 224,
        date: "4.11.2005",
        categories: ["Seinen", "Action", "Supernatural"],
        imgCover: "https://media.libris.to/jacket/01348903_berserk.jpg",
        imgPanels: ["https://i.pinimg.com/736x/07/28/b9/0728b970ae219619b83fb64ea3431020.jpg", "https://64.media.tumblr.com/acd466ceb19e78395e00bc2c22a5122c/6a975e344cbf7da6-ff/s500x750/428e250ae2303fa1bf22fee5e35992492dd74562.jpg",
         "https://pbs.twimg.com/media/Ew4ymZYWUAAt4Wd.jpg"],    
    },
    {
        title: "Berserk Volume 4",
        series: "Berserk",
        authors: ["Kentaro Miura"],
        language: "EN",
        isBestseller: true,
        discount: 25,
        rating: 5,
        numberOfRatings: 1,
        price: 294,
        desc: `His name is Guts, the Black Swordsman, a feared warrior spoken of only in whispers. Bearer of a gigantic sword, an iron hand, and the scars of countless battles and tortures, his flesh is also indelibly marked with The Brand, an unholy symbol that draws the forces of darkness to him and dooms him as their sacrifice. But Guts won't take his fate lying down; he'll cut a crimson swath of carnage through the ranks of the damned - and anyone else foolish enough to oppose him!`,
        pages: 224,
        date: "4.11.2003",
        categories: ["Seinen", "Action", "Supernatural"],
        imgCover: "https://media.libris.to/jacket/04238660_berserk.jpg",
        imgPanels: ["https://i.pinimg.com/736x/07/28/b9/0728b970ae219619b83fb64ea3431020.jpg", "https://64.media.tumblr.com/acd466ceb19e78395e00bc2c22a5122c/6a975e344cbf7da6-ff/s500x750/428e250ae2303fa1bf22fee5e35992492dd74562.jpg",
         "https://pbs.twimg.com/media/Ew4ymZYWUAAt4Wd.jpg"],    
    },
    {
        title: "Berserk Volume 5",
        series: "Berserk",
        authors: ["Kentaro Miura"],
        language: "EN",
        isBestseller: true,
        discount: 25,
        rating: 5,
        numberOfRatings: 1,
        price: 334,
        desc: `His name is Guts, the Black Swordsman, a feared warrior spoken of only in whispers. Bearer of a gigantic sword, an iron hand, and the scars of countless battles and tortures, his flesh is also indelibly marked with The Brand, an unholy symbol that draws the forces of darkness to him and dooms him as their sacrifice. But Guts won't take his fate lying down; he'll cut a crimson swath of carnage through the ranks of the damned - and anyone else foolish enough to oppose him!`,
        pages: 224,
        date: "4.11.2003",
        categories: ["Seinen", "Action", "Supernatural"],
        imgCover: "https://media.libris.to/jacket/04238667_berserk.jpg",
        imgPanels: ["https://i.pinimg.com/736x/07/28/b9/0728b970ae219619b83fb64ea3431020.jpg", "https://64.media.tumblr.com/acd466ceb19e78395e00bc2c22a5122c/6a975e344cbf7da6-ff/s500x750/428e250ae2303fa1bf22fee5e35992492dd74562.jpg",
         "https://pbs.twimg.com/media/Ew4ymZYWUAAt4Wd.jpg"],    
    },
    {
        title: "Berserk Volume 6",
        series: "Berserk",
        authors: ["Kentaro Miura"],
        language: "EN",
        isBestseller: true,
        discount: 25,
        rating: 5,
        numberOfRatings: 1,
        price: 299,
        desc: `His name is Guts, the Black Swordsman, a feared warrior spoken of only in whispers. Bearer of a gigantic sword, an iron hand, and the scars of countless battles and tortures, his flesh is also indelibly marked with The Brand, an unholy symbol that draws the forces of darkness to him and dooms him as their sacrifice. But Guts won't take his fate lying down; he'll cut a crimson swath of carnage through the ranks of the damned - and anyone else foolish enough to oppose him!`,
        pages: 224,
        date: "4.11.2003",
        categories: ["Seinen", "Action", "Supernatural"],
        imgCover: "https://media.libris.to/jacket/04238668_berserk.jpg",
        imgPanels: ["https://i.pinimg.com/736x/07/28/b9/0728b970ae219619b83fb64ea3431020.jpg", "https://64.media.tumblr.com/acd466ceb19e78395e00bc2c22a5122c/6a975e344cbf7da6-ff/s500x750/428e250ae2303fa1bf22fee5e35992492dd74562.jpg",
         "https://pbs.twimg.com/media/Ew4ymZYWUAAt4Wd.jpg"],    
    },


    {
        title: "Vagabond Vol. 1",
        series: "Vagabond",
        authors: ["Takehiko Inoue"],
        language: "EN",
        rating: 5,
        numberOfRatings: 1,
        price: 450,
        discount: 60,
        desc: `Striving for enlightenment by way of the sword, Miyamoto Musashi is prepared to cut down anyone who stands in his way. Vagabond is an action-packed portrayal of the life and times of the quintessential warrior-philosopher - the most celebrated samurai of all time! Shinmen Takezo is destined to become the legendary sword-saint, Miyamoto Musashi - perhaps the most renowned samurai of all time. For now, Takezo is a cold-hearted killer, who will take on anyone in mortal combat to make a name for himself. This is the journey of a wild young brute who strives to reach enlightenment by way of the sword - fighting on the edge of death.`,
        pages: 728,
        date: "8.6.2014",
        categories: ["Seinen", "Action", "Adventure"],
        imgCover: "https://media.libris.to/jacket/12976060_vagabond-01.jpg",
        imgPanels: ["https://i.pinimg.com/736x/07/28/b9/0728b970ae219619b83fb64ea3431020.jpg", "https://64.media.tumblr.com/acd466ceb19e78395e00bc2c22a5122c/6a975e344cbf7da6-ff/s500x750/428e250ae2303fa1bf22fee5e35992492dd74562.jpg",
         "https://pbs.twimg.com/media/Ew4ymZYWUAAt4Wd.jpg"],    
    },
    {
        title: "Vagabond Vol. 2",
        series: "Vagabond",
        authors: ["Takehiko Inoue"],
        language: "EN",
        rating: 5,
        numberOfRatings: 1,
        price: 390,
        discount: 60,
        desc: `Striving for enlightenment by way of the sword, Miyamoto Musashi is prepared to cut down anyone who stands in his way. Vagabond is an action-packed portrayal of the life and times of the quintessential warrior-philosopher - the most celebrated samurai of all time! Shinmen Takezo is destined to become the legendary sword-saint, Miyamoto Musashi - perhaps the most renowned samurai of all time. For now, Takezo is a cold-hearted killer, who will take on anyone in mortal combat to make a name for himself. This is the journey of a wild young brute who strives to reach enlightenment by way of the sword - fighting on the edge of death.`,
        pages: 728,
        date: "8.6.2014",
        categories: ["Seinen", "Action", "Adventure"],
        imgCover: "https://media.libris.to/jacket/12976061_vagabond-02.jpg",
        imgPanels: ["https://i.pinimg.com/736x/07/28/b9/0728b970ae219619b83fb64ea3431020.jpg", "https://64.media.tumblr.com/acd466ceb19e78395e00bc2c22a5122c/6a975e344cbf7da6-ff/s500x750/428e250ae2303fa1bf22fee5e35992492dd74562.jpg",
         "https://pbs.twimg.com/media/Ew4ymZYWUAAt4Wd.jpg"],    
    },
    {
        title: "Vagabond Vol. 3",
        series: "Vagabond",
        authors: ["Takehiko Inoue"],
        language: "EN",
        rating: 5,
        numberOfRatings: 1,
        price: 450,
        discount: 30,
        desc: `Striving for enlightenment by way of the sword, Miyamoto Musashi is prepared to cut down anyone who stands in his way. Vagabond is an action-packed portrayal of the life and times of the quintessential warrior-philosopher - the most celebrated samurai of all time! Shinmen Takezo is destined to become the legendary sword-saint, Miyamoto Musashi - perhaps the most renowned samurai of all time. For now, Takezo is a cold-hearted killer, who will take on anyone in mortal combat to make a name for himself. This is the journey of a wild young brute who strives to reach enlightenment by way of the sword - fighting on the edge of death.`,
        pages: 728,
        date: "8.6.2014",
        categories: ["Seinen", "Action", "Adventure"],
        imgCover: "https://m.media-amazon.com/images/I/91KDm4kUI2L.jpg",
        imgPanels: ["https://i.pinimg.com/736x/07/28/b9/0728b970ae219619b83fb64ea3431020.jpg", "https://64.media.tumblr.com/acd466ceb19e78395e00bc2c22a5122c/6a975e344cbf7da6-ff/s500x750/428e250ae2303fa1bf22fee5e35992492dd74562.jpg",
         "https://pbs.twimg.com/media/Ew4ymZYWUAAt4Wd.jpg"],    
    },
    {
        title: "Vagabond Vol. 4",
        series: "Vagabond",
        authors: ["Takehiko Inoue"],
        language: "EN",
        rating: 5,
        numberOfRatings: 1,
        price: 428,
        discount: 30,
        desc: `Striving for enlightenment by way of the sword, Miyamoto Musashi is prepared to cut down anyone who stands in his way. Vagabond is an action-packed portrayal of the life and times of the quintessential warrior-philosopher - the most celebrated samurai of all time! Shinmen Takezo is destined to become the legendary sword-saint, Miyamoto Musashi - perhaps the most renowned samurai of all time. For now, Takezo is a cold-hearted killer, who will take on anyone in mortal combat to make a name for himself. This is the journey of a wild young brute who strives to reach enlightenment by way of the sword - fighting on the edge of death.`,
        pages: 728,
        date: "8.6.2014",
        categories: ["Seinen", "Action", "Adventure"],
        imgCover: "https://m.media-amazon.com/images/I/51gl5FlJwLL._AC_SY780_.jpg",
        imgPanels: ["https://i.pinimg.com/736x/07/28/b9/0728b970ae219619b83fb64ea3431020.jpg", "https://64.media.tumblr.com/acd466ceb19e78395e00bc2c22a5122c/6a975e344cbf7da6-ff/s500x750/428e250ae2303fa1bf22fee5e35992492dd74562.jpg",
         "https://pbs.twimg.com/media/Ew4ymZYWUAAt4Wd.jpg"],    
    },
    {
        title: "Vagabond Vol. 5",
        series: "Vagabond",
        authors: ["Takehiko Inoue"],
        language: "EN",
        rating: 5,
        numberOfRatings: 1,        
        price: 450,
        discount: 30,
        desc: `Striving for enlightenment by way of the sword, Miyamoto Musashi is prepared to cut down anyone who stands in his way. Vagabond is an action-packed portrayal of the life and times of the quintessential warrior-philosopher - the most celebrated samurai of all time! Shinmen Takezo is destined to become the legendary sword-saint, Miyamoto Musashi - perhaps the most renowned samurai of all time. For now, Takezo is a cold-hearted killer, who will take on anyone in mortal combat to make a name for himself. This is the journey of a wild young brute who strives to reach enlightenment by way of the sword - fighting on the edge of death.`,
        pages: 728,
        date: "8.6.2014",
        categories: ["Seinen", "Action", "Adventure"],
        imgCover: "https://m.media-amazon.com/images/I/513eRcVoRkL._AC_SY780_.jpg",
        imgPanels: ["https://i.pinimg.com/736x/07/28/b9/0728b970ae219619b83fb64ea3431020.jpg", "https://64.media.tumblr.com/acd466ceb19e78395e00bc2c22a5122c/6a975e344cbf7da6-ff/s500x750/428e250ae2303fa1bf22fee5e35992492dd74562.jpg",
         "https://pbs.twimg.com/media/Ew4ymZYWUAAt4Wd.jpg"],    
    },
    {
        title: "Goodnight Punpun 1",
        series: "Goodnight Punpun",
        authors: ["Inio Asano"],
        language: "EN",
        isBestseller: true,
        rating: 5,
        discount: 25,
        numberOfRatings: 0,
        price: 688,
        desc: `Meet Punpun Punyama. He's an average kid in an average town.

        He wants to win a Nobel Prize and save the world.
        
        He wants to go far away with his true love.
        
        He wants to find some porn.
        
        But Punpun's life is about to unravel...`,              
        pages: 448,
        date: "01.04.2016",
        categories: ["Psychological", "Drama"],
        imgCover: "https://www.knihydobrovsky.cz/thumbs/book-detail-fancy-box/mod_eshop/produkty/395769829/80.jpg",
        imgPanels: ["https://ih1.redbubble.net/image.261632499.7181/st,small,845x845-pad,1000x1000,f8f8f8.u3.jpg", "https://64.media.tumblr.com/9e23336e5766599c043bba339252616d/tumblr_p9cyptinrQ1w3yzuso1_1280.jpg", "https://64.media.tumblr.com/e1bbfac351585ec033d7ba1bcead1cff/bc7ac4ae49cc54da-7b/s540x810/8fc7b2ab2fc636a588783919104b61a4fe30ed64.pnj"],    
    },
    {
        title: "Goodnight Punpun 2",
        series: "Goodnight Punpun",
        authors: ["Inio Asano"],
        language: "EN",
        rating: 3.5,
        discount: 25,
        numberOfRatings: 0,
        price: 495,
        desc: `Meet Punpun Punyama. He's an average kid in an average town.

        He wants to win a Nobel Prize and save the world.
        
        He wants to go far away with his true love.
        
        He wants to find some porn.
        
        But Punpun's life is about to unravel...`,              
        pages: 448,
        date: "01.04.2016",
        categories: ["Psychological", "Drama"],
        imgCover: "https://media.libris.to/jacket/02966821_goodnight-punpun-vol-2.jpg",
        imgPanels: ["https://ih1.redbubble.net/image.261632499.7181/st,small,845x845-pad,1000x1000,f8f8f8.u3.jpg", "https://64.media.tumblr.com/9e23336e5766599c043bba339252616d/tumblr_p9cyptinrQ1w3yzuso1_1280.jpg", "https://64.media.tumblr.com/e1bbfac351585ec033d7ba1bcead1cff/bc7ac4ae49cc54da-7b/s540x810/8fc7b2ab2fc636a588783919104b61a4fe30ed64.pnj"],    
    },
    {
        title: "Goodnight Punpun 3",
        series: "Goodnight Punpun",
        authors: ["Inio Asano"],
        language: "EN",
        rating: 4,
        numberOfRatings: 0,
        price: 555,
        discount: 10,
        isBestseller: true,
        desc: `Meet Punpun Punyama. He's an average kid in an average town.

        He wants to win a Nobel Prize and save the world.
        
        He wants to go far away with his true love.
        
        He wants to find some porn.
        
        But Punpun's life is about to unravel...`,              
        pages: 448,
        date: "01.04.2016",
        categories: ["Psychological", "Drama"],
        imgCover: "https://media.libris.to/jacket/10044978_goodnight-punpun-vol-3.jpg",
        imgPanels: ["https://ih1.redbubble.net/image.261632499.7181/st,small,845x845-pad,1000x1000,f8f8f8.u3.jpg", "https://64.media.tumblr.com/9e23336e5766599c043bba339252616d/tumblr_p9cyptinrQ1w3yzuso1_1280.jpg", "https://64.media.tumblr.com/e1bbfac351585ec033d7ba1bcead1cff/bc7ac4ae49cc54da-7b/s540x810/8fc7b2ab2fc636a588783919104b61a4fe30ed64.pnj"],    
    },
    {
        title: "Goodnight Punpun 4",
        series: "Goodnight Punpun",
        authors: ["Inio Asano"],
        language: "EN",
        rating: 5,
        numberOfRatings: 0,
        price: 500,
        discount: 10,
        desc: `Meet Punpun Punyama. He's an average kid in an average town.

        He wants to win a Nobel Prize and save the world.
        
        He wants to go far away with his true love.
        
        He wants to find some porn.
        
        But Punpun's life is about to unravel...`,              
        pages: 456,
        date: "01.04.2016",
        categories: ["Psychological", "Drama"],
        imgCover: "https://media.libris.to/jacket/12080758_goodnight-punpun-vol-4.jpg",
        imgPanels: ["https://ih1.redbubble.net/image.261632499.7181/st,small,845x845-pad,1000x1000,f8f8f8.u3.jpg", "https://64.media.tumblr.com/9e23336e5766599c043bba339252616d/tumblr_p9cyptinrQ1w3yzuso1_1280.jpg", "https://64.media.tumblr.com/e1bbfac351585ec033d7ba1bcead1cff/bc7ac4ae49cc54da-7b/s540x810/8fc7b2ab2fc636a588783919104b61a4fe30ed64.pnj"],    
    },
    {
        title: "Goodnight Punpun 5",
        series: "Goodnight Punpun",
        authors: ["Inio Asano"],
        language: "EN",
        rating: 4.5,
        numberOfRatings: 0,
        price: 480,
        discount: 10,
        desc: `Meet Punpun Punyama. He's an average kid in an average town.

        He wants to win a Nobel Prize and save the world.
        
        He wants to go far away with his true love.
        
        He wants to find some porn.
        
        But Punpun's life is about to unravel...`,              
        pages: 448,
        date: "01.04.2016",
        categories: ["Psychological", "Drama"],
        imgCover: "https://media.libris.to/jacket/13668506_goodnight-punpun-vol-5.jpg",
        imgPanels: ["https://ih1.redbubble.net/image.261632499.7181/st,small,845x845-pad,1000x1000,f8f8f8.u3.jpg", "https://64.media.tumblr.com/9e23336e5766599c043bba339252616d/tumblr_p9cyptinrQ1w3yzuso1_1280.jpg", "https://64.media.tumblr.com/e1bbfac351585ec033d7ba1bcead1cff/bc7ac4ae49cc54da-7b/s540x810/8fc7b2ab2fc636a588783919104b61a4fe30ed64.pnj"],    
    },
    {
        title: "Goodnight Punpun 6",
        series: "Goodnight Punpun",
        authors: ["Inio Asano"],
        language: "EN",
        rating: 4,
        numberOfRatings: 0,
        price: 596,
        discount: 10,
        desc: `Meet Punpun Punyama. He's an average kid in an average town.

        He wants to win a Nobel Prize and save the world.
        
        He wants to go far away with his true love.
        
        He wants to find some porn.
        
        But Punpun's life is about to unravel...`,              
        pages: 448,
        date: "01.04.2016",
        categories: ["Psychological", "Drama"],
        imgCover: "https://media.libris.to/jacket/15446853_goodnight-punpun-vol-6.jpg",
        imgPanels: ["https://ih1.redbubble.net/image.261632499.7181/st,small,845x845-pad,1000x1000,f8f8f8.u3.jpg", "https://64.media.tumblr.com/9e23336e5766599c043bba339252616d/tumblr_p9cyptinrQ1w3yzuso1_1280.jpg", "https://64.media.tumblr.com/e1bbfac351585ec033d7ba1bcead1cff/bc7ac4ae49cc54da-7b/s540x810/8fc7b2ab2fc636a588783919104b61a4fe30ed64.pnj"],    
    },
    {
        title: "Goodnight Punpun 7",
        series: "Goodnight Punpun",
        authors: ["Inio Asano"],
        language: "EN",
        rating: 5,
        discount: 10,
        numberOfRatings: 0,
        price: 419,
        desc: `Meet Punpun Punyama. He's an average kid in an average town.

        He wants to win a Nobel Prize and save the world.
        
        He wants to go far away with his true love.
        
        He wants to find some porn.
        
        But Punpun's life is about to unravel...`,              
        pages: 272,
        date: "01.04.2016",
        categories: ["Psychological", "Drama"],
        imgCover: "https://media.libris.to/jacket/15446854_goodnight-punpun-vol-7.jpg",
        imgPanels: ["https://ih1.redbubble.net/image.261632499.7181/st,small,845x845-pad,1000x1000,f8f8f8.u3.jpg", "https://64.media.tumblr.com/9e23336e5766599c043bba339252616d/tumblr_p9cyptinrQ1w3yzuso1_1280.jpg", "https://64.media.tumblr.com/e1bbfac351585ec033d7ba1bcead1cff/bc7ac4ae49cc54da-7b/s540x810/8fc7b2ab2fc636a588783919104b61a4fe30ed64.pnj"],    
    },
    {
        title: "Uzumaki (3-in-1 Deluxe Edition)",
        series: "",
        authors: ["Junji Ito"],
        language: "EN",
        rating: 4.5,
        isBestseller: true,
        numberOfRatings: 0,
        price: 581,
        isNew: true,
        discount: 5,
        desc: `Kurouzu-cho, a small fogbound town on the coast of Japan, is cursed.

        According to Shuichi Saito, the withdrawn boyfriend of teenager Kirie Goshima, their town is haunted not by a person or being but a pattern: UZUMAKI, the spiral—the hypnotic secret shape of the world. The bizarre masterpiece horror manga is now available all in a single volume.
        
        Fall into a whirlpool of terror!`,              
        pages: 648,
        date: "16.10.2013",
        categories: ["Horror", "Mystery", "Supernatural"],
        imgCover: "https://media.libris.to/jacket/01987210_uzumaki-3-in-1-deluxe-edition.jpg",
        imgPanels: ["http://cdn.pastemagazine.com/www/articles/2015/06/22/Uzamaki.jpg", 
        "https://images.squarespace-cdn.com/content/v1/57825361440243db4a4b7830/1596717030741-A99KW1KBKTKNOMVLZBBN/Jinji-ito-horror-manga-uzumaki-shojo-horror-manga-tomie-Kawakami-Kirie-Goshima-spirals-Kurouzu-cho-The-Enigma-of-Amigara-Fault-The-Hanging-Balloons", 
        "https://i0.wp.com/croneandcasket.com/wp-content/uploads/2017/08/awitf7x.jpg?resize=676%2C998&ssl=1"],    
    },
    {
        title: "Tomie: Complete Deluxe Edition",
        series: "",
        authors: ["Junji Ito"],
        language: "CZ",
        rating: 5,
        discount: 5,
        isNew: true,
        numberOfRatings: 1,
        price: 169,
        desc: `The complete classic horror series, now available in a single deluxe volume.

        Murdered again and again, one girl always comes back for more... Tomie Kawakami is a femme fatale with long black hair and a beauty mark just under her left eye. She can seduce nearly any man, and drive them to murder as well, even though the victim is often Tomie herself.
        
        While one lover seeks to keep her for himself, another grows terrified of the immortal succubus. But soon they realize no matter how many times they kill her, the world will never be free of Tomie.`,
        pages: 548,
        date: "16.10.2013",
        categories: ["Horror", "Mystery", "Supernatural"],
        imgCover: "https://media.libris.to/jacket/10921887_tomie.jpg",
        imgPanels: ["https://i.imgur.com/f9AnnYK.png", "https://static1.mangayeh.com/manga/chapter/601918f12b30c165f1ce79a9/601a26bedfcb41783d6e59fa/kanshikan_tsunemori_akane_1_26.jpg", "https://static.mangajar.com/pages/952/66044/zpuq5vYhcfiyhrLUuOkjdIorYqUlQKQUf9pRBCbT.webp"],    
    },
    {
        title: "World's End Harem: Fantasia Vol. 1",
        series: "World's End Harem",
        authors: ["Savan"],
        language: "EN",
        rating: 2,
        numberOfRatings: 1,
        price: 315,
        desc: "Svět budoucnosti, kde duševní stav rozhoduje o vašem životě. Pod neustálým dohledem systému Sybil má každý obyvatel svůj vlastní psycho-pass, zařízení, které na základě stresu a dalších faktorů určuje index zločinnosti. Je pak na zaměstnancích Úřadu veřejné bezpečnosti, aby vykonali rozsudek, který nad potenciálními i skutečnými zločinci systém vynese.Po odhalení, že staří lidé umírali kvůli genetickým časovačům v jejich orgánech, pátrá inspektor Šin’ja Kógami se svým týmem po chirurgovi, jenž je za jejich zavedení nejspíš zodpovědný. Pátrání je přivede až ke zvláštnímu pečovatelskému domu, kolem něhož se vynořují nové a nové skutečnosti.",
        pages: 196,
        date: "01.06.2019",
        categories: ["Harem", "Romance", "Fantasy"],
        imgCover: "https://media.libris.to/jacket/22515833_world-s-end-harem-fantasia-vol-1.jpg",
        imgPanels: ["https://s2.mbcdnv6.xyz/file/img-mbuddy/manga/worlds-end-harem-fantasia/chapter-5/37.jpg", "https://isekaiscan.com/wp-content/uploads/WP-manga/data/manga_5cc49ccfead1a/c361d4daf023a8fb687af77e9e966ae8/15.jpg", "https://image.mangabtt.com//Upload/ImageContent/20221016/41647/28fec211-46b8-46c4-850a-7aafd2975f25-950609.jpg"],    
    },
    {
        title: "World's End Harem: Fantasia Vol. 2",
        series: "World's End Harem",
        authors: ["Savan"],
        language: "EN",
        rating: 1,
        numberOfRatings: 1,
        price: 315,
        desc: "Svět budoucnosti, kde duševní stav rozhoduje o vašem životě. Pod neustálým dohledem systému Sybil má každý obyvatel svůj vlastní psycho-pass, zařízení, které na základě stresu a dalších faktorů určuje index zločinnosti. Je pak na zaměstnancích Úřadu veřejné bezpečnosti, aby vykonali rozsudek, který nad potenciálními i skutečnými zločinci systém vynese.Po odhalení, že staří lidé umírali kvůli genetickým časovačům v jejich orgánech, pátrá inspektor Šin’ja Kógami se svým týmem po chirurgovi, jenž je za jejich zavedení nejspíš zodpovědný. Pátrání je přivede až ke zvláštnímu pečovatelskému domu, kolem něhož se vynořují nové a nové skutečnosti.",
        pages: 196,
        date: "01.06.2019",
        categories: ["Harem", "Romance", "Fantasy",],
        imgCover: "https://media.libris.to/jacket/24661051_world-s-end-harem-fantasia-vol-2.jpg",
        imgPanels: ["https://s2.mbcdnv6.xyz/file/img-mbuddy/manga/worlds-end-harem-fantasia/chapter-5/37.jpg", "https://isekaiscan.com/wp-content/uploads/WP-manga/data/manga_5cc49ccfead1a/c361d4daf023a8fb687af77e9e966ae8/15.jpg", "https://image.mangabtt.com//Upload/ImageContent/20221016/41647/28fec211-46b8-46c4-850a-7aafd2975f25-950609.jpg"],    
    },
    {
        title: "World's End Harem: Fantasia Vol. 3",
        series: "World's End Harem",
        authors: ["Savan"],
        language: "EN",
        rating: 3,
        numberOfRatings: 1,
        price: 328,
        desc: "Svět budoucnosti, kde duševní stav rozhoduje o vašem životě. Pod neustálým dohledem systému Sybil má každý obyvatel svůj vlastní psycho-pass, zařízení, které na základě stresu a dalších faktorů určuje index zločinnosti. Je pak na zaměstnancích Úřadu veřejné bezpečnosti, aby vykonali rozsudek, který nad potenciálními i skutečnými zločinci systém vynese.Po odhalení, že staří lidé umírali kvůli genetickým časovačům v jejich orgánech, pátrá inspektor Šin’ja Kógami se svým týmem po chirurgovi, jenž je za jejich zavedení nejspíš zodpovědný. Pátrání je přivede až ke zvláštnímu pečovatelskému domu, kolem něhož se vynořují nové a nové skutečnosti.",
        pages: 196,
        date: "01.06.2019",
        categories: ["Harem", "Romance", "Fantasy"],
        imgCover: "https://media.libris.to/jacket/25161190_world-s-end-harem-fantasia-vol-3.jpg",
        imgPanels: ["https://s2.mbcdnv6.xyz/file/img-mbuddy/manga/worlds-end-harem-fantasia/chapter-5/37.jpg", "https://isekaiscan.com/wp-content/uploads/WP-manga/data/manga_5cc49ccfead1a/c361d4daf023a8fb687af77e9e966ae8/15.jpg", "https://image.mangabtt.com//Upload/ImageContent/20221016/41647/28fec211-46b8-46c4-850a-7aafd2975f25-950609.jpg"],    
    },
    {
        title: "Psycho-Pass: Inspector Shinya Kogami 1",
        series: "Psycho Pass",
        authors: ["Goto Midori", "Sai Natsuo"],
        language: "CZ",
        rating: 4,
        isNew: true,
        numberOfRatings: 1,
        price: 189,
        desc: "Svět budoucnosti, kde duševní stav rozhoduje o vašem životě. Pod neustálým dohledem systému Sybil má každý obyvatel svůj vlastní psycho-pass, zařízení, které na základě stresu a dalších faktorů určuje index zločinnosti. Je pak na zaměstnancích Úřadu veřejné bezpečnosti, aby vykonali rozsudek, který nad potenciálními i skutečnými zločinci systém vynese.Po odhalení, že staří lidé umírali kvůli genetickým časovačům v jejich orgánech, pátrá inspektor Šin’ja Kógami se svým týmem po chirurgovi, jenž je za jejich zavedení nejspíš zodpovědný. Pátrání je přivede až ke zvláštnímu pečovatelskému domu, kolem něhož se vynořují nové a nové skutečnosti.",
        pages: 180,
        date: "14.12.2022",
        categories: ["Sci-Fi", "Action", "Psychological"],
        imgCover: "https://www.knihydobrovsky.cz/thumbs/book-detail-fancy-box/mod_eshop/produkty/p/psycho-pass-inspector-shinya-kogami-1-9788027713844.jpg",
        imgPanels: ["https://i.imgur.com/f9AnnYK.png", "https://static1.mangayeh.com/manga/chapter/601918f12b30c165f1ce79a9/601a26bedfcb41783d6e59fa/kanshikan_tsunemori_akane_1_26.jpg", "https://static.mangajar.com/pages/952/66044/zpuq5vYhcfiyhrLUuOkjdIorYqUlQKQUf9pRBCbT.webp"],    
    },
    {
        title: "Psycho-Pass: Inspector Shinya Kogami 2",
        series: "Psycho Pass",
        authors: ["Goto Midori","Sai Natsuo"],
        language: "CZ",
        rating: 5,
        numberOfRatings: 1,
        isNew: true,
        price: 169,
        desc: "Svět budoucnosti, kde duševní stav rozhoduje o vašem životě. Pod neustálým dohledem systému Sybil má každý obyvatel svůj vlastní psycho-pass, zařízení, které na základě stresu a dalších faktorů určuje index zločinnosti. Je pak na zaměstnancích Úřadu veřejné bezpečnosti, aby vykonali rozsudek, který nad potenciálními i skutečnými zločinci systém vynese.Po odhalení, že staří lidé umírali kvůli genetickým časovačům v jejich orgánech, pátrá inspektor Šin’ja Kógami se svým týmem po chirurgovi, jenž je za jejich zavedení nejspíš zodpovědný. Pátrání je přivede až ke zvláštnímu pečovatelskému domu, kolem něhož se vynořují nové a nové skutečnosti.",
        pages: 180,
        date: "14.12.2022",
        categories: ["Sci-Fi", "Action", "Psychological"],
        imgCover: "https://www.knihydobrovsky.cz/thumbs/book-detail-fancy-box/mod_eshop/produkty/p/psycho-pass-inspector-shinya-kogami-2-9788027713851.jpg",
        imgPanels: ["https://i.imgur.com/f9AnnYK.png", "https://static1.mangayeh.com/manga/chapter/601918f12b30c165f1ce79a9/601a26bedfcb41783d6e59fa/kanshikan_tsunemori_akane_1_26.jpg", "https://static.mangajar.com/pages/952/66044/zpuq5vYhcfiyhrLUuOkjdIorYqUlQKQUf9pRBCbT.webp"],    
    },
    {
        title: "Psycho-Pass: Inspector Shinya Kogami 3",
        series: "Psycho Pass",
        authors: ["Goto Midori", "Sai Natsuo"],
        language: "CZ",
        rating: 5,
        numberOfRatings: 1,
        isNew: true,
        price: 159,
        desc: "Svět budoucnosti, kde duševní stav rozhoduje o vašem životě. Pod neustálým dohledem systému Sybil má každý obyvatel svůj vlastní psycho-pass, zařízení, které na základě stresu a dalších faktorů určuje index zločinnosti. Je pak na zaměstnancích Úřadu veřejné bezpečnosti, aby vykonali rozsudek, který nad potenciálními i skutečnými zločinci systém vynese.Po odhalení, že staří lidé umírali kvůli genetickým časovačům v jejich orgánech, pátrá inspektor Šin’ja Kógami se svým týmem po chirurgovi, jenž je za jejich zavedení nejspíš zodpovědný. Pátrání je přivede až ke zvláštnímu pečovatelskému domu, kolem něhož se vynořují nové a nové skutečnosti.",
        pages: 180,
        date: "14.12.2022",
        categories: ["Sci-Fi", "Action", "Psychological"],
        imgCover: "https://www.knihydobrovsky.cz/thumbs/book-detail-fancy-box/mod_eshop/produkty/p/psycho-pass-inspector-shinya-kogami-3-9788027713868.jpg",
        imgPanels: ["https://i.imgur.com/f9AnnYK.png", "https://static1.mangayeh.com/manga/chapter/601918f12b30c165f1ce79a9/601a26bedfcb41783d6e59fa/kanshikan_tsunemori_akane_1_26.jpg", "https://static.mangajar.com/pages/952/66044/zpuq5vYhcfiyhrLUuOkjdIorYqUlQKQUf9pRBCbT.webp"],    
    },

    {
        title: "Berserk Volume 1",
        series: "Berserk",
        authors: ["Kentaro Miura"],
        language: "EN",
        rating: 5,
        numberOfRatings: 1,
        price: 334,
        desc: `His name is Guts, the Black Swordsman, a feared warrior spoken of only in whispers. Bearer of a gigantic sword, an iron hand, and the scars of countless battles and tortures, his flesh is also indelibly marked with The Brand, an unholy symbol that draws the forces of darkness to him and dooms him as their sacrifice. But Guts won't take his fate lying down; he'll cut a crimson swath of carnage through the ranks of the damned - and anyone else foolish enough to oppose him!`,
        pages: 224,
        date: "4.11.2003",
        categories: ["Seinen", "Action", "Supernatural"],
        imgCover: "https://media.libris.to/jacket/04238626_berserk-volume-1-the-black-swordsman.jpg",
        imgPanels: ["https://i.pinimg.com/736x/07/28/b9/0728b970ae219619b83fb64ea3431020.jpg", "https://64.media.tumblr.com/acd466ceb19e78395e00bc2c22a5122c/6a975e344cbf7da6-ff/s500x750/428e250ae2303fa1bf22fee5e35992492dd74562.jpg",
         "https://pbs.twimg.com/media/Ew4ymZYWUAAt4Wd.jpg"],    
    },
    {
        title: "Berserk Volume 1",
        series: "Berserk",
        authors: ["Kentaro Miura"],
        language: "EN",
        rating: 5,
        numberOfRatings: 1,
        price: 334,
        desc: `His name is Guts, the Black Swordsman, a feared warrior spoken of only in whispers. Bearer of a gigantic sword, an iron hand, and the scars of countless battles and tortures, his flesh is also indelibly marked with The Brand, an unholy symbol that draws the forces of darkness to him and dooms him as their sacrifice. But Guts won't take his fate lying down; he'll cut a crimson swath of carnage through the ranks of the damned - and anyone else foolish enough to oppose him!`,
        pages: 224,
        date: "4.11.2003",
        categories: ["Seinen", "Action", "Supernatural"],
        imgCover: "https://media.libris.to/jacket/04238626_berserk-volume-1-the-black-swordsman.jpg",
        imgPanels: ["https://i.pinimg.com/736x/07/28/b9/0728b970ae219619b83fb64ea3431020.jpg", "https://64.media.tumblr.com/acd466ceb19e78395e00bc2c22a5122c/6a975e344cbf7da6-ff/s500x750/428e250ae2303fa1bf22fee5e35992492dd74562.jpg",
         "https://pbs.twimg.com/media/Ew4ymZYWUAAt4Wd.jpg"],    
    },







]